# Data update script for ....

In [243]:
import pandas as pd

tables = pd.read_html("https://euenergy.live/")
len(tables)

1

In [235]:
# Find the table I am interested in
df = tables[0]
df

        Unnamed: 0 Unnamed: 1   €/MWh
0       🇦🇹 Austria       ▲40%  277.80
1       🇧🇪 Belgium       ▲78%  316.48
2      🇧🇬 Bulgaria       ▲71%  301.76
3   🇨🇭 Switzerland       ▲45%  308.63
4       🇨🇿 Czechia       ▲78%  296.63
5       🇩🇪 Germany       ▲99%  291.64
6      ¹🇩🇰 Denmark       ▲35%  189.91
7      ²🇩🇰 Denmark       ▲37%  188.57
8       🇪🇪 Estonia       ▲19%  272.75
9         🇪🇸 Spain      ▼-12%  103.36
10      🇫🇮 Finland       ▲19%  272.75
11       🇫🇷 France       ▲84%  318.85
12       🇬🇷 Greece       ▲57%  319.03
13      🇭🇷 Croatia       ▲74%  302.83
14      🇭🇺 Hungary       ▲71%  301.23
15        🇮🇹 Italy       ▲63%  331.77
16    🇱🇹 Lithuania       ▲19%  272.75
17       🇱🇻 Latvia       ▲19%  272.75
18  🇳🇱 Netherlands       ▲57%  324.05
19      ¹🇳🇴 Norway       ▲34%  189.02
20      ²🇳🇴 Norway       ▲34%  189.02
21      ³🇳🇴 Norway       ▲34%   75.09
22      ⁴🇳🇴 Norway       ▲50%   46.82
23      ⁵🇳🇴 Norway       ▲34%  189.02
24       🇵🇱 Poland        ▲4%  197.73
25     🇵🇹 Portugal      ▼-12%  103.36
26      🇷🇴 Romania       ▲71%  301.76
27       🇷🇸 Serbia       ▲56%  297.49
28      ¹🇸🇪 Sweden       ▲58%  187.76
29      ²🇸🇪 Sweden       ▲58%  187.76
30      ³🇸🇪 Sweden       ▲37%  188.57
31      ⁴🇸🇪 Sweden       ▲37%  188.57
32     🇸🇮 Slovenia       ▲75%  303.60
33     🇸🇰 Slovakia       ▲69%  300.27

In [236]:
#Rename the columns
df = df.rename(columns={"Unnamed: 0": "country", "Unnamed: 1": "development", "€/MWh": "price"})
df

           country development   price
0       🇦🇹 Austria        ▲40%  277.80
1       🇧🇪 Belgium        ▲78%  316.48
2      🇧🇬 Bulgaria        ▲71%  301.76
3   🇨🇭 Switzerland        ▲45%  308.63
4       🇨🇿 Czechia        ▲78%  296.63
5       🇩🇪 Germany        ▲99%  291.64
6      ¹🇩🇰 Denmark        ▲35%  189.91
7      ²🇩🇰 Denmark        ▲37%  188.57
8       🇪🇪 Estonia        ▲19%  272.75
9         🇪🇸 Spain       ▼-12%  103.36
10      🇫🇮 Finland        ▲19%  272.75
11       🇫🇷 France        ▲84%  318.85
12       🇬🇷 Greece        ▲57%  319.03
13      🇭🇷 Croatia        ▲74%  302.83
14      🇭🇺 Hungary        ▲71%  301.23
15        🇮🇹 Italy        ▲63%  331.77
16    🇱🇹 Lithuania        ▲19%  272.75
17       🇱🇻 Latvia        ▲19%  272.75
18  🇳🇱 Netherlands        ▲57%  324.05
19      ¹🇳🇴 Norway        ▲34%  189.02
20      ²🇳🇴 Norway        ▲34%  189.02
21      ³🇳🇴 Norway        ▲34%   75.09
22      ⁴🇳🇴 Norway        ▲50%   46.82
23      ⁵🇳🇴 Norway        ▲34%  189.02
24       🇵🇱 Poland         ▲4%  197.73
25     🇵🇹 Portugal       ▼-12%  103.36
26      🇷🇴 Romania        ▲71%  301.76
27       🇷🇸 Serbia        ▲56%  297.49
28      ¹🇸🇪 Sweden        ▲58%  187.76
29      ²🇸🇪 Sweden        ▲58%  187.76
30      ³🇸🇪 Sweden        ▲37%  188.57
31      ⁴🇸🇪 Sweden        ▲37%  188.57
32     🇸🇮 Slovenia        ▲75%  303.60
33     🇸🇰 Slovakia        ▲69%  300.27

In [237]:
#Remove the emojis
df = df.astype(str).apply(lambda x: x.str.encode('ascii', 'ignore').str.decode('ascii'))

In [238]:
# And rename the Czech Republic to match datawrapper
df['country'] = df['country'].str.replace('Czechia', 'Czech Rep.')

In [239]:
# Turn the price column into a float
df['price'] = df['price'].astype(float)

In [240]:
# Group the data by country and find the mean price per country to get the prices on country leegl
df = round(df.groupby('country').price.mean())

In [241]:
df

country
 Austria        278.0
 Belgium        316.0
 Bulgaria       302.0
 Croatia        303.0
 Czech Rep.     297.0
 Denmark        189.0
 Estonia        273.0
 Finland        273.0
 France         319.0
 Germany        292.0
 Greece         319.0
 Hungary        301.0
 Italy          332.0
 Latvia         273.0
 Lithuania      273.0
 Netherlands    324.0
 Norway         138.0
 Poland         198.0
 Portugal       103.0
 Romania        302.0
 Serbia         297.0
 Slovakia       300.0
 Slovenia       304.0
 Spain          103.0
 Sweden         188.0
 Switzerland    309.0
Name: price, dtype: float64

In [242]:
df.to_csv("europaenergy.csv")