# Data update script for ....

In [204]:
#url = "https://www.sportsbettingdime.com/soccer/world-cup-odds/"


url = "https://euenergy.live/"

In [205]:
import pandas as pd

tables = pd.read_html(url)
len(tables)

1

In [206]:
# Find the table I am interested in
df = tables[0]
df

        Unnamed: 0 Unnamed: 1   €/MWh
0       🇦🇹 Austria       ▼-8%  244.48
1       🇧🇪 Belgium       ▼-7%  239.81
2      🇧🇬 Bulgaria       ▼-8%  238.49
3   🇨🇭 Switzerland      ▼-16%  251.02
4       🇨🇿 Czechia      ▼-10%  239.34
5       🇩🇪 Germany       ▼-7%  239.17
6      ¹🇩🇰 Denmark       ▼-7%  238.76
7      ²🇩🇰 Denmark       ▼-8%  237.36
8       🇪🇪 Estonia       ▼-8%  261.71
9         🇪🇸 Spain       ▼-8%  130.21
10      🇫🇮 Finland       ▼-8%  261.71
11       🇫🇷 France       ▼-8%  240.18
12       🇬🇷 Greece       ▼-4%  250.28
13      🇭🇷 Croatia      ▼-10%  239.42
14      🇭🇺 Hungary      ▼-11%  239.48
15        🇮🇹 Italy      ▼-13%  262.64
16    🇱🇹 Lithuania       ▼-8%  261.71
17       🇱🇻 Latvia       ▼-8%  261.71
18  🇳🇱 Netherlands       ▼-4%  239.21
19      ¹🇳🇴 Norway       ▼-2%  190.25
20      ²🇳🇴 Norway       ▼-2%  190.25
21      ³🇳🇴 Norway       ▲11%   68.57
22      ⁴🇳🇴 Norway        ▲8%   61.25
23      ⁵🇳🇴 Norway       ▼-2%  190.25
24       🇵🇱 Poland       ▼-3%  232.93
25     🇵🇹 Portugal       ▼-8%  130.21
26      🇷🇴 Romania       ▼-8%  238.49
27       🇷🇸 Serbia       ▼-8%  242.13
28      ¹🇸🇪 Sweden      ▼-28%  173.33
29      ²🇸🇪 Sweden      ▼-28%  173.33
30      ³🇸🇪 Sweden       ▼-9%  232.27
31      ⁴🇸🇪 Sweden       ▼-8%  236.20
32     🇸🇮 Slovenia      ▼-11%  239.48
33     🇸🇰 Slovakia      ▼-11%  239.47

In [207]:
df = df.rename(columns={"Unnamed: 0": "country", "Unnamed: 1": "development", "€/MWh": "price"})
df

           country development   price
0       🇦🇹 Austria        ▼-8%  244.48
1       🇧🇪 Belgium        ▼-7%  239.81
2      🇧🇬 Bulgaria        ▼-8%  238.49
3   🇨🇭 Switzerland       ▼-16%  251.02
4       🇨🇿 Czechia       ▼-10%  239.34
5       🇩🇪 Germany        ▼-7%  239.17
6      ¹🇩🇰 Denmark        ▼-7%  238.76
7      ²🇩🇰 Denmark        ▼-8%  237.36
8       🇪🇪 Estonia        ▼-8%  261.71
9         🇪🇸 Spain        ▼-8%  130.21
10      🇫🇮 Finland        ▼-8%  261.71
11       🇫🇷 France        ▼-8%  240.18
12       🇬🇷 Greece        ▼-4%  250.28
13      🇭🇷 Croatia       ▼-10%  239.42
14      🇭🇺 Hungary       ▼-11%  239.48
15        🇮🇹 Italy       ▼-13%  262.64
16    🇱🇹 Lithuania        ▼-8%  261.71
17       🇱🇻 Latvia        ▼-8%  261.71
18  🇳🇱 Netherlands        ▼-4%  239.21
19      ¹🇳🇴 Norway        ▼-2%  190.25
20      ²🇳🇴 Norway        ▼-2%  190.25
21      ³🇳🇴 Norway        ▲11%   68.57
22      ⁴🇳🇴 Norway         ▲8%   61.25
23      ⁵🇳🇴 Norway        ▼-2%  190.25
24       🇵🇱 Poland        ▼-3%  232.93
25     🇵🇹 Portugal        ▼-8%  130.21
26      🇷🇴 Romania        ▼-8%  238.49
27       🇷🇸 Serbia        ▼-8%  242.13
28      ¹🇸🇪 Sweden       ▼-28%  173.33
29      ²🇸🇪 Sweden       ▼-28%  173.33
30      ³🇸🇪 Sweden        ▼-9%  232.27
31      ⁴🇸🇪 Sweden        ▼-8%  236.20
32     🇸🇮 Slovenia       ▼-11%  239.48
33     🇸🇰 Slovakia       ▼-11%  239.47

In [208]:
df = df.astype(str).apply(lambda x: x.str.encode('ascii', 'ignore').str.decode('ascii'))

In [209]:
df['country'] = df['country'].str.replace('Czechia', 'Czech Rep.')

In [210]:
df['price'] = df['price'].astype(float)

#df = df.groupby('Country').Price.mean()
#df

In [211]:
df = round(df.groupby('country').price.mean())

In [212]:
df

country
 Austria        244.0
 Belgium        240.0
 Bulgaria       238.0
 Croatia        239.0
 Czech Rep.     239.0
 Denmark        238.0
 Estonia        262.0
 Finland        262.0
 France         240.0
 Germany        239.0
 Greece         250.0
 Hungary        239.0
 Italy          263.0
 Latvia         262.0
 Lithuania      262.0
 Netherlands    239.0
 Norway         140.0
 Poland         233.0
 Portugal       130.0
 Romania        238.0
 Serbia         242.0
 Slovakia       239.0
 Slovenia       239.0
 Spain          130.0
 Sweden         204.0
 Switzerland    251.0
Name: price, dtype: float64

In [213]:
df.to_csv("europaenergy.csv")