# Data update script for ....

In [172]:
#url = "https://www.sportsbettingdime.com/soccer/world-cup-odds/"


url = "https://euenergy.live/"

In [173]:
import pandas as pd

tables = pd.read_html(url)
len(tables)

1

In [174]:
# Find the table I am interested in
df = tables[0]
df

        Unnamed: 0 Unnamed: 1   €/MWh
0       🇦🇹 Austria        ▲2%  266.24
1       🇧🇪 Belgium       ▲11%  258.30
2      🇧🇬 Bulgaria       ▼-2%  258.31
3   🇨🇭 Switzerland        ▲9%  300.12
4       🇨🇿 Czechia        ▲8%  266.19
5       🇩🇪 Germany        ▲9%  257.93
6      ¹🇩🇰 Denmark        ▲8%  256.96
7      ²🇩🇰 Denmark        ▲8%  256.96
8       🇪🇪 Estonia        ▲5%  285.99
9         🇪🇸 Spain        ▲3%  141.39
10      🇫🇮 Finland        ▲5%  285.99
11       🇫🇷 France       ▲10%  261.02
12       🇬🇷 Greece      ▼-11%  261.97
13      🇭🇷 Croatia        ▲3%  266.92
14      🇭🇺 Hungary        ▲2%  270.07
15        🇮🇹 Italy        ▲8%  300.86
16    🇱🇹 Lithuania        ▲5%  285.99
17       🇱🇻 Latvia        ▲5%  285.99
18  🇳🇱 Netherlands        ▲8%  248.30
19      ¹🇳🇴 Norway       ▲17%  193.46
20      ²🇳🇴 Norway       ▲17%  193.46
21      ³🇳🇴 Norway       ▼-6%   61.86
22      ⁴🇳🇴 Norway       ▲54%   56.93
23      ⁵🇳🇴 Norway       ▲17%  193.46
24       🇵🇱 Poland       ▼-2%  239.89
25     🇵🇹 Portugal        ▲3%  141.39
26      🇷🇴 Romania       ▼-3%  258.31
27       🇷🇸 Serbia        ▲7%  263.87
28      ¹🇸🇪 Sweden        ▲1%  239.82
29      ²🇸🇪 Sweden        ▲1%  239.82
30      ³🇸🇪 Sweden        ▲8%  255.04
31      ⁴🇸🇪 Sweden        ▲8%  256.46
32     🇸🇮 Slovenia        ▲5%  267.77
33     🇸🇰 Slovakia        ▲4%  269.87

In [175]:
df = df.rename(columns={"Unnamed: 0": "country", "Unnamed: 1": "development", "€/MWh": "price"})
df

           country development   price
0       🇦🇹 Austria         ▲2%  266.24
1       🇧🇪 Belgium        ▲11%  258.30
2      🇧🇬 Bulgaria        ▼-2%  258.31
3   🇨🇭 Switzerland         ▲9%  300.12
4       🇨🇿 Czechia         ▲8%  266.19
5       🇩🇪 Germany         ▲9%  257.93
6      ¹🇩🇰 Denmark         ▲8%  256.96
7      ²🇩🇰 Denmark         ▲8%  256.96
8       🇪🇪 Estonia         ▲5%  285.99
9         🇪🇸 Spain         ▲3%  141.39
10      🇫🇮 Finland         ▲5%  285.99
11       🇫🇷 France        ▲10%  261.02
12       🇬🇷 Greece       ▼-11%  261.97
13      🇭🇷 Croatia         ▲3%  266.92
14      🇭🇺 Hungary         ▲2%  270.07
15        🇮🇹 Italy         ▲8%  300.86
16    🇱🇹 Lithuania         ▲5%  285.99
17       🇱🇻 Latvia         ▲5%  285.99
18  🇳🇱 Netherlands         ▲8%  248.30
19      ¹🇳🇴 Norway        ▲17%  193.46
20      ²🇳🇴 Norway        ▲17%  193.46
21      ³🇳🇴 Norway        ▼-6%   61.86
22      ⁴🇳🇴 Norway        ▲54%   56.93
23      ⁵🇳🇴 Norway        ▲17%  193.46
24       🇵🇱 Poland        ▼-2%  239.89
25     🇵🇹 Portugal         ▲3%  141.39
26      🇷🇴 Romania        ▼-3%  258.31
27       🇷🇸 Serbia         ▲7%  263.87
28      ¹🇸🇪 Sweden         ▲1%  239.82
29      ²🇸🇪 Sweden         ▲1%  239.82
30      ³🇸🇪 Sweden         ▲8%  255.04
31      ⁴🇸🇪 Sweden         ▲8%  256.46
32     🇸🇮 Slovenia         ▲5%  267.77
33     🇸🇰 Slovakia         ▲4%  269.87

In [176]:
df = df.astype(str).apply(lambda x: x.str.encode('ascii', 'ignore').str.decode('ascii'))

In [177]:
df['country'] = df['country'].str.replace('Czechia', 'Czech Rep.')

In [178]:
df['price'] = df['price'].astype(float)

#df = df.groupby('Country').Price.mean()
#df

In [179]:
df = round(df.groupby('country').price.mean())

In [180]:
df

country
 Austria        266.0
 Belgium        258.0
 Bulgaria       258.0
 Croatia        267.0
 Czech Rep.     266.0
 Denmark        257.0
 Estonia        286.0
 Finland        286.0
 France         261.0
 Germany        258.0
 Greece         262.0
 Hungary        270.0
 Italy          301.0
 Latvia         286.0
 Lithuania      286.0
 Netherlands    248.0
 Norway         140.0
 Poland         240.0
 Portugal       141.0
 Romania        258.0
 Serbia         264.0
 Slovakia       270.0
 Slovenia       268.0
 Spain          141.0
 Sweden         248.0
 Switzerland    300.0
Name: price, dtype: float64

In [181]:
df.to_csv("euenergy.csv")